// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTask = "task"

// Task mapped from table <task>
type Task struct {
	ID            int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID        int32          `gorm:"column:user_id;not null" json:"user_id"`
	SchoolID      string         `gorm:"column:school_id;not null" json:"school_id"`           // 学校ID
	StudentID     string         `gorm:"column:student_id;not null" json:"student_id"`         // 学生ID
	SchoolAddress string         `gorm:"column:school_address;not null" json:"school_address"` // 学校地址
	CreateTime    time.Time      `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP(3)" json:"create_time"`
	UpdateTime    time.Time      `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP(3)" json:"update_time"`
	DeleteTime    gorm.DeletedAt `gorm:"column:delete_time" json:"delete_time"`
}

// TableName Task's table name
func (*Task) TableName() string {
	return TableNameTask
}
