// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID         int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username   string         `gorm:"column:username;not null" json:"username"` // 用户名，唯一
	Password   string         `gorm:"column:password;not null" json:"password"` // 密码
	CreateTime time.Time      `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP(3)" json:"create_time"`
	UpdateTime time.Time      `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP(3)" json:"update_time"`
	DeleteTime gorm.DeletedAt `gorm:"column:delete_time" json:"delete_time"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
